
public class DieGame {

	/*
	Name: Narendra Gopalam
	Student Number: A00245541

	Program Description: DieGame - Create Die Structure and roll to play DieGame
	*/
//Start of die DieGame
	public static void main(String[] args) {
// creating three objects of different types of die
		//d6 die is generated by using no argument constructor
		Die d6=new Die();
		//d20 die/object is generated by using one argument constructor where it takes no of sides as a argument
		Die d20=new Die(20);
		//d10 die is generated by using two arguments constructor where it takes name of the die and no of sides
		Die d10=new Die("Percentile",10);
		//the below statement prints the current side up of a die
		//roll method will generate a random number to know the current side up of a die in the Accessor
		System.out.println("The current side up for "+d6.getName()+" is "+d6.getCurrent_side_up());
		System.out.println("The current side up for "+d20.getName()+" is "+d20.getCurrent_side_up());
		System.out.println("The current side up for "+d10.getName()+" is "+d10.getCurrent_side_up());

		//Testing the roll method by rolling the die
		System.out.print("\nTesting the roll method\n");
		System.out.println("\nRolling the "+d6.getName()+"...");
		System.out.println("The new value is "+d6.getCurrent_side_up());
		System.out.println("Rolling the "+d20.getName()+"...");
		System.out.println("The new value is "+d20.getCurrent_side_up());
		System.out.println("Rolling the "+d10.getName()+"...");
		System.out.println("The new value is "+d10.getCurrent_side_up());


		//now we are rolling the die d20 until we roll the max number of d20 die i.e, 20
		System.out.println("Setting the "+d20.getName()+" to show 20...");
		//for loop contains a if condition where weare cheking the the current side up is 20 or not
		//the loop will iterate until the condition is satisfied
		 for(int i=0,j=1;i<j;i++,j++)
		 {
			 if(d20.getCurrent_side_up()==20)
			 {
				 System.out.println("The side up is now 20. Finally.");
				 //the below statement is to terminate from the loop  after the d20 die current side is 20
				 j=i;
			 }
		 }

// Bounus game YAHTZEE
		System.out.println("\n-----");
		System.out.println("BONUS");
		System.out.println("-----");

// creating 5 d6 die using one argument constructor
		Die d1=new Die(6);
		Die d2=new Die(6);
		Die d3=new Die(6);
		Die d4=new Die(6);
		Die d5=new Die(6);

// the below loop contains nested if which will iterate until all the die's roll the same number and its YAHTZEE...!
					for(int i=0,j=1;i<j;i++,j++)
					 {
						 if(d1.getCurrent_side_up()==d2.getCurrent_side_up())
						 {
							 if(d2.getCurrent_side_up()==d3.getCurrent_side_up())
							 {
								 if(d3.getCurrent_side_up()==d4.getCurrent_side_up())
								 {
									 if(d4.getCurrent_side_up()==d5.getCurrent_side_up())
									 {
										 System.out.println("YAHTZEE! It took "+j+" rolls");
										 j=i;
									 }
								 }
							 }
						 }
					 }

	}



}
